### ISSUE TITLE
AIRLAW: Please modify Q96 an add Q97

### ISSUE THREAD

**Issue by ArthMaster** [florisporro/svelte-exam-trainer#1]
AIRLAW:  Please make Question 96 a bit more clear by using a comma as a separator.

96 With respect to aircraft accident and incident investigation, what are the three categories regarding aircraft occurrences?
[x]  Event, Crash, Disaster
[x]  Happening, Event, Serious event
[v] Incident, Serious incident, Accident
[x] Event, Serious event, Accident

AIRLAW: Please add new Question 97.

97 What is the primary purpose of an aircraft accident investigation?
[x] To Determine the guilty party and draw legal consequences
[x] To clarify questions of liability within the meaning of compensation for passengers
[v] To identify the reasons and work out safety recommendations
[x] To work for the public prosecutor and help to follow-up flight accidents

P.S. Keep up the good work!

**Comment by florisporro** [comment]
@ArthMaster thanks for opening the first issue! Just fixed / added these with #[b9084c0](https://github.com/florisporro/svelte-exam-trainer/commit/b9084c081ba9a3ea34c9211abb4d05aa78f5795c).
