### ISSUE TITLE
Incorrect answers...

### ISSUE THREAD

**Issue by benniAvia** [florisporro/svelte-exam-trainer#12]
Navigation: 

Incorrect answers. E.g. 

38 1000 ft equal**_s_**...

30 Km
3000 M
300 M
30 M

None of the answers are correct. 

Kms. It is 116.13
Meters 116128.80

**Comment by florisporro** [comment]
The first part of the question is in reference to the question number, namely question 38 of chapter Navigation. So the question is: 1000ft equals how many meters?

To answer, divide 1000 by 3,281 (3,3) to get roughly 300 meters. So C is correct.
